# Utilise l'image OpenJDK 19 comme base
FROM openjdk:19

# Définit le répertoire de travail de l'application
WORKDIR /app

# Copie le fichier jar de l'application dans le répertoire de travail
COPY ./out/artifacts/sExterne-REST-Latinos/sExterne-REST-Latinos.jar /app

# Expose le port 8181 pour que l'application puisse être accessible depuis l'extérieur
EXPOSE 8181

# Démarre l'application
CMD ["java", "-jar", "sExterne-REST-Latinos.jar"]